# Generated by Django 6.0.5 on 2026-05-06 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('midterm_score', models.FloatField()),
                ('assignment_completion', models.FloatField()),
                ('attendance_rate', models.FloatField()),
                ('study_hours', models.FloatField()),
                ('previous_grade', models.CharField(max_length=50)),
                ('motivation', models.CharField(max_length=50)),
                ('parental_support', models.CharField(max_length=50)),
                ('learning_style', models.CharField(max_length=50)),
                ('prediction', models.CharField(blank=True, max_length=10, null=True)),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='authentication.professor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
