# Generated by Django 6.0 on 2026-05-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_created_at_student_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='assignment_completion',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='student',
            name='attendance_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='student',
            name='learning_style',
            field=models.CharField(blank=True, default='Visual', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='midterm_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='student',
            name='motivation',
            field=models.CharField(blank=True, default='Medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='parental_support',
            field=models.CharField(blank=True, default='Medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='previous_grade',
            field=models.CharField(blank=True, default='C', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='study_hours',
            field=models.FloatField(default=0.0),
        ),
    ]
