# Generated by Django 6.0 on 2026-05-19 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_level_student_student_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_grade', models.CharField(max_length=2)),
                ('midterm_score', models.FloatField()),
                ('attendance_rate', models.FloatField()),
                ('study_hours', models.FloatField()),
                ('previous_grade', models.CharField(blank=True, max_length=50)),
                ('motivation', models.CharField(blank=True, max_length=50)),
                ('parental_support', models.CharField(blank=True, max_length=50)),
                ('learning_style', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_history', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
