# Generated by Django 6.0 on 2026-06-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_predictionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionhistory',
            name='predicted_grade',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='prediction',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
