# Generated by Django 6.0.5 on 2026-05-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
