# Generated by Django 6.0 on 2026-05-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_professor_created_at_professor_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
